<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<script src="/resources/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-select/js/dataTables.select.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-select/js/select.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-buttons/js/buttons.flash.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-colreorder/js/colReorder.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-colreorder/js/dataTables.colReorder.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-fixedcolumns/js/dataTables.fixedColumns.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-fixedcolumns/js/fixedColumns.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-fixedheader/js/dataTables.fixedHeader.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-fixedheader/js/fixedHeader.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-keytable/js/dataTables.keyTable.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-keytable/js/keyTable.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-rowgroup/js/dataTables.rowGroup.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-rowgroup/js/rowGroup.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-rowreorder/js/dataTables.rowReorder.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-rowreorder/js/rowReorder.bootstrap4.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-scroller/js/dataTables.scroller.min.js"></script>
<script src="/resources/adminlte/plugins/datatables-scroller/js/scroller.bootstrap4.min.js"></script>